stan-core:
  stanPath: .stan
  excludes:
    - CHANGELOG.md
    - docs
    - package-lock.json
  imports:
    entity-manager:
      - ../entity-manager/.stan/system/stan.requirements.md
      - ../entity-manager/.stan/system/stan.todo.md
      - ../entity-manager/dist/index.d.ts
      - ../entity-manager/.stan/interop/entity-client-dynamodb/**
    entity-manager-demo:
      - ../entity-manager-demo/.stan/system/stan.requirements.md
      - ../entity-manager-demo/.stan/system/stan.todo.md
      - ../entity-manager-demo/dist/index.d.ts
      - ../entity-manager-demo/.stan/interop/entity-client-dynamodb/**
    entity-tools:
      - ../entity-tools/.stan/system/stan.requirements.md
      - ../entity-tools/.stan/system/stan.todo.md
      - ../entity-tools/dist/index.d.ts
      - ../entity-tools/.stan/interop/entity-client-dynamodb/**
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck
    lint:
      script: npm run lint:fix
      warnPattern: \\d+:\\d+\\s+warning
    test: npm run test -- --no-color
    build: cross-env NO_COLOR=1 npm run build
    docs:
      script: npm run docs -- --emit none
      warnPattern: ^(?!.*@smithy\\/types#ChecksumConstructor)(?!.*@smithy\\/smithy-client#DefaultsMode).*\\[warning\\]
    knip: npm run knip
