stan-core:
  stanPath: .stan
  excludes:
    - CHANGELOG.md
    - docs/**
    - package-lock.json
  includes:
    - .stan/imports/**
  imports:
    '@commander-js/extra-typings':
      - node_modules/@commander-js/extra-typings/index.d.ts
    '@karmaniverous/entity-manager':
      - ../entity-manager/.stan/interop/entity-client-dynamodb/**
      - ../entity-manager/guides/stan-assistant-guide.md
    '@karmaniverous/entity-manager-demo':
      - ../entity-manager-demo/.stan/interop/entity-client-dynamodb/**
    '@karmaniverous/entity-tools':
      - ../entity-tools/.stan/interop/entity-client-dynamodb/**
      - ../entity-tools/guides/stan-assistant-guide.md
    '@karmaniverous/get-dotenv':
      - ../get-dotenv/.stan/interop/entity-client-dynamodb/**
      - ../get-dotenv/guides/stan-assistant-guide.md
    '@karmaniverous/smoz':
      - ../smoz/.stan/interop/entity-client-dynamodb/**
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    build: cross-env NO_COLOR=1 npm run build
    typecheck: npm run typecheck
    lint:
      script: npm run lint:fix
      warnPattern: \\d+:\\d+\\s+warning
    test: npm run test -- --no-color
    docs:
      script: npm run docs -- --emit none
      warnPattern: ^(?!.*@smithy\\/types#ChecksumConstructor)(?!.*@smithy\\/smithy-client#DefaultsMode).*\\[warning\\]
    knip: npm run knip
